### ISSUE TITLE
Composer not working. Plugin not published?

### ISSUE THREAD

**Issue by WHITE-developer** [kennethormandy/craft-s3securedownloads#1]
When trying to install the plugin via composer I can't get it to work.
Looks like you forgot to publish it on packagist.org as I can't find it there? https://packagist.org/?query=kennethormandy%2Fcraft-s3securedownloads

**Comment by kennethormandy** [comment]
You’re right, thanks. It’s up now: https://packagist.org/packages/kennethormandy/craft-s3securedownloads
