### ISSUE TITLE
Craft 4

### ISSUE THREAD

**Issue by petehjfd** [kennethormandy/craft-s3securedownloads#10]
Hi, is there any plan to support Craft 4?

Thanks

**Comment by kennethormandy** [comment]
Hi, yes, I am planning on adding support for Craft 4.

I’ve just released v3.1.0, which had a featured that needed to be in a v3.x release first.

**Comment by petehjfd** [comment]
That's great news, thanks.  Any chance you can give an ETA?

**Comment by kennethormandy** [comment]
Hi, I don’t have an ETA for this. I need to upgrade the test suite site to Craft 4 as well.

I’m guessing it won’t actually need any changes other than running [the Rector rules](https://github.com/craftcms/rector) on the plugin. If you wanted to give that a go, I’d be happy to merge a PR into a beta or alpha release for easier installation. Although if you get to that point, it would probably also be relatively easy to install your own branch.

**Comment by rosskenney** [comment]
Hi @kennethormandy do you have a preferred method for the Craft 3 vs Craft 4 versions in your repo? In my fork I changed the version to 4.0.0. I also am doing the dev in a v4 branch if that makes sense for your flow. I have run through rector and fixed some things with phpstan. Found a few other little things that needed adjustment and or clean up. I need to do some testing to make sure it works, but it is well underway.

**Comment by kennethormandy** [comment]
@rosskenney Hey, that is awesome, thank you so much. I can also add you to the test suite repo if you’d like? There are Codeception tests for everything, but it needs the parent Craft site to run.

On a v4 or craft-4 branch or similar makes sense to me.

You mean 4.0.0 for the minimum Craft version, correct? Yes that makes sense to me too.

**Comment by rosskenney** [comment]
I'd be happy to have the test env. By 4.0.0 I was talking the plugins version number. Currently it's in the 3.x.x and should stay there for Craft 3

**Comment by kennethormandy** [comment]
@rosskenney I’ve added you. The tests need S3 to run, and they are running on CI now, but that might not be super helpful to you as you are working locally. I might see about updating this repo so the parent Craft site lives here too.

**Comment by rosskenney** [comment]
@kennethormandy Awesome, my plan is to work more on this tomorrow along with another plugin. I have a local craft 3 and 4 version running for testing other plugins I work on, but would love to see your testing env for this. Maybe we can see about a zip up with the db dump sent so I can incorporate it into my env. I did some tests the other day and I believe everything is working but want to make sure. Thanks!

**Comment by kennethormandy** [comment]
@rosskenney I invited you on GitHub, and there is a `seed.sql` database dump, but the tests use an S3 bucket so it might not be that helpful. If you have it on a branch, I can probably upgrade the parent Craft site and run the tests against it to double check.

**Comment by chadcrowell** [comment]
@kennethormandy any chance we can get this tested, pulled, and released? 2 sites waiting for it...

**Comment by chadcrowell** [comment]
Btw I ran rector on the Craft 3 version and it took all of 5 minutes to get it set for Craft 4.

**Comment by rosskenney** [comment]
@chadcrowell Sorry I lost track of helping on this. I have a fork that I ran rector and fixed any issues. Seemed good with the limited tests I did, but probably could use some more testing. I can open a PR for it to be a RC for use and further testing.

**Comment by rosskenney** [comment]
@chadcrowell Nevermind, I see https://github.com/kennethormandy/craft-s3securedownloads/pull/11 looks like pretty much what I did.

**Comment by chadcrowell** [comment]
I downloaded #11 and tested it locally (no unit tests- real world functional usage) and its working nicely.

**Comment by rosskenney** [comment]
I'd say get it out as a beta for now @kennethormandy. Then is can be used and tested further in real world settings.

**Comment by kennethormandy** [comment]
Agreed, you can install this now with:

```sh
composer require kennethormandy/craft-s3securedownloads:^4.0.0-beta.1
```

Thanks for testing this personally @chadcrowell and @rosskenney, and of course to @harry2909 for opening the PR!
