### ISSUE TITLE
Template Error in Commerce Email?

### ISSUE THREAD

**Issue by jacobgraf** [kennethormandy/craft-s3securedownloads#5]
I am using your plugin to generate a download link in a Commerce email. Everything works fine when I test the email template in the browser, but when Craft tries to generate and send the Commerce email, I get the following error. Any ideas?

`2020-02-20 06:04:21 [-][1][-][error][craft\commerce\services\Emails::sendEmail] Email template parse error for email “Event - Registration”. Order: “da45cef”. Template error: “Unknown "getSignedUrl" function.” /home/forge/getconnected.works/templates/_emails/events/registrationBsp1.twig:19`

**Craft:** Pro 3.4.6.1
**Commerce:** Pro 3.0.9
**S3 Secure Downloads:** 2.2.1

**Comment by kennethormandy** [comment]
Hi, thanks for opening an issue.

I’m guessing this doesn’t work because `getSignedUrl` redirects you, rather than being directly to the AWS URL. There could be a different function for that, or at least a nicer error message.

One option that works now would be to link to the order complete page, and have the download link generated there. Then you have the option of checking if the person is logged in, and the person can still generate a new link again later.

**Comment by jacobgraf** [comment]
Unfortunately, we don't even have an order complete page outside of "Thank You". Everything is done over email in our case.

I'm not sure the redirect is the issue though because it's not even making it that far. It just can't access the getSignedUrl function when it runs. Works fine in my template test, but the Craft Commerce Email parser can't access the plugin service method. Hmm.

**Comment by jacobgraf** [comment]
So I worked with Craft support and they found a way to access the service method manually which gets me into the function....

{{ craft.app.plugins.getPlugin('s3securedownloads').s3securedownloads.getSignedUrl(asset.id) }}

But then I get this error...

https://share.getcloudapp.com/Z4u5JEp5

**Comment by jacobgraf** [comment]
It's working! It was an error because it was in local dev and I didn't have the DB synced. Thanks for all your help!

**Comment by kennethormandy** [comment]
Glad to hear it, thanks for the update!

**Comment by jacobgraf** [comment]
Ok, I guess I spoke too soon.

I just got an email from the client. Still getting the email error. After troubleshooting, I am finding the following error...

`Trying to get property 'filename' of non-object`

Again, this works fine when the template is rendered normally using `{{ getSignedUrl(asset.id) }}` but doesn't work when Craft Commerce tries to parse and send the email.

Any other ideas here?

**Comment by kennethormandy** [comment]
Does the asset for sure exist? Or could this be related to your different environments like you mentioned earlier? Or are there some emails that don’t have assets at all? It sounds like there is no asset for the plugin to work with—there should be a better error message, but other than that it doesn’t sound specific to the plugin. I would try something like:

```twig
{% set asset = entry.myAssetField.one() %}
{% if asset %}
  <a href="{{ getSignedUrl(asset.id) }}">{{ asset }}</a>
{% else %}
  <p>Sorry, we couldn’t find the PDF for your order. Please get in touch.</p>
{% endif %}
```

…and see what you get from there.

**Comment by jacobgraf** [comment]
Yes, if I just output `{{ asset.filename }}` in the template, it shows the filename, but for some reason, the plugin can't access it when using the long-form call...

`{{ craft.app.plugins.getPlugin('s3securedownloads').s3securedownloads.getSignedUrl(asset.id) }}`
