### ISSUE TITLE
The authorization mechanism you have provided is not supported

### ISSUE THREAD

**Issue by peteheaney** [kennethormandy/craft-s3securedownloads#6]
Hi, I'm getting the following error when attempting to open a file:

```
InvalidRequestThe authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
```

Is this because the plugin isn't using AWS Signature Version 4?  If so, are there any plans to upgrade the signature version the plugin uses?

Thanks

**Comment by kennethormandy** [comment]
Hey, thanks for opening an issue. You’re correct about the reason.

I have a beta of a new major release that uses AWS Signature Version 4. Testing with a bucket in `ca-central-1` that also only supports the new approach, everything seemed fine. I think this will fix the problem for you.

You can give the new version a try:

```sh
composer require kennethormandy/craft-s3securedownloads:3.0.0-beta.1
```

Let me know how that works for you!

**Comment by peteheaney** [comment]
Thanks @kennethormandy 

I had to go with a different approach to get the job done, but I'll give this new version a try as soon as I have some time.

**Comment by peteheaney** [comment]
Hi @kennethormandy I just wanted to let you know that I finally got around to installing the v3 beta and it worked like a charm.

Thanks for your help.

**Comment by kennethormandy** [comment]
@peteheaney Thanks, I appreciate that!
