### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by nfq** [kennethormandy/craft-s3securedownloads#9]
Hi,

Is there any way to use this with GraphQL?

**Comment by kennethormandy** [comment]
Hi @nfq,

Can you give me a bit more context about what you’re looking to do here? 

The URLs need to be generated at the time they are going to be used, so they aren’t stored in the database, and therefore not something I would have thought about making available via GraphQL.

Are you looking to generate signed links on a separate site that uses Craft as a headless CMS, on the same site in a client-side component?

You could POST to a controller action that uses the SignUrl service from this plugin, and returns the signed URL to your component.

The controller action endpoints don’t exist for that in this plugin yet, but I could see the value in adding that. In the meantime, they could be part of your own module that uses the SignUrl service from this plugin.

Is that the sort of thing you are after?
